// Variable glossary: the content that used to live in a standalone "Variables ▾" dropdown
// (index.html), now the single source of truth for the hover/tap tooltips wired up by
// tooltip.js everywhere a bare symbol like "I_p" or "λ_q" appears on the page, with no
// change to the wording itself. `term` is the tooltip's small heading; `html` is its body
// (may contain the same inline markup -- <sub>, <strong>, etc. -- as the rest of the page).
export const GLOSSARY = {
  beta: {
    term: "β — plasma beta",
    html: `Plasma pressure as a fraction of magnetic pressure, β = p̄/(B<sub>t</sub>²/2μ₀) — how efficiently the confining field is being used to hold plasma pressure. The <strong>Steady state</strong> presets below (Low β / High β) vary this qualitatively via the solver's own arbitrary-unit pressure amplitude, not a calibrated real value (see "Units" in how this works); <strong>β<sub>N</sub></strong> further down this list is the real, calibrated, normalized version, computed from the actual operating point. Real devices hit a hard MHD stability ceiling on β (see β<sub>N</sub>'s Troyon limit) well before running out of fuel or heating power.`,
  },
  Bt: {
    term: "B_t — toroidal field",
    html: `The main confining field, running the long way around the torus, generated by the external coils (schematic in the 3D view). Tesla (T). Charged particles gyrate around field lines at the cyclotron frequency ω<sub>c</sub> = qB/m, which is the whole confinement mechanism in one equation — stronger B means a tighter gyroradius and better confinement, which is why β<sub>N</sub> below is normalized by it.`,
  },
  Ip: {
    term: "I_p — plasma current",
    html: `The toroidal current flowing in the plasma itself (MA), driven inductively (transformer action off the central solenoid) or by auxiliary current-drive. By Ampère's law it's what sets the poloidal field B<sub>θ</sub>(a) = μ₀I<sub>p</sub>/2πa at the edge — this page derives B<sub>θ</sub> this way to get l<sub>i</sub>, q<sub>95</sub>, and λ<sub>q</sub> from a real-unit I<sub>p</sub> input.`,
  },
  Hmode: {
    term: "H-mode / L-mode",
    html: `Two distinct edge-transport states. Above a threshold auxiliary heating power P<sub>LH</sub> (Martin08 scaling, shown live in "Power and fusion"), sheared E×B flow at the edge suppresses turbulent transport and forms a steep edge transport barrier — H-mode — roughly doubling energy confinement time over L-mode. This is a real bifurcation in the underlying turbulence, not just a labeling convention.`,
  },
  betaN: {
    term: "β_N — normalized beta",
    html: `β = p̄/(B<sub>t</sub>²/2μ₀) is plasma pressure as a fraction of magnetic pressure; β<sub>N</sub> = β[%]·a[m]·B<sub>t</sub>[T]/I<sub>p</sub>[MA] further normalizes by current and size so devices of different scale are comparable. The Troyon/no-wall MHD stability limit is β<sub>N</sub> ≲ 2.8 — above it, kink/ballooning modes tend to trigger a disruption.`,
  },
  q95: {
    term: "q_95 — edge safety factor",
    html: `q(ψ) = dΦ<sub>tor</sub>/dΦ<sub>pol</sub>, the number of times a field line circles toroidally per poloidal circuit, evaluated at the flux surface enclosing 95% of the poloidal flux. Low-order rational q (q=1, 2, 3/2…) resonates with current-driven MHD modes; real devices avoid q<sub>95</sub> ≲ 2 to stay clear of the disruptive m/n=2/1 tearing mode.`,
  },
  Wth: {
    term: "W_th — thermal stored energy",
    html: `W<sub>th</sub> = (3/2)∫(n<sub>e</sub>T<sub>e</sub> + n<sub>i</sub>T<sub>i</sub>)dV, the total kinetic energy in the plasma's electrons and ions (joules, shown in MJ). It's the numerator in τ<sub>E</sub> = W<sub>th</sub>/P<sub>loss</sub> below — literally "how much energy is stored, divided by how fast it's leaking."`,
  },
  H98: {
    term: "H_98 — confinement quality",
    html: `H<sub>98</sub> = τ<sub>E,actual</sub>/τ<sub>E,IPB98(y,2)</sub>, the measured confinement time divided by the ITER Physics Basis empirical scaling-law prediction for a shot with the same I<sub>p</sub>, B<sub>t</sub>, density, heating power, and geometry. It's how real experiments report "we're confining as well as the database says we should" (H<sub>98</sub>≈1) or better/worse.`,
  },
  Te0: {
    term: "T_e0 — central electron temperature",
    html: `Peak electron temperature at the magnetic axis, in keV (1 keV ≈ 1.16×10⁷ K). Sets the Bosch-Hale fusion reactivity ⟨σv⟩(T) — this is the single biggest lever on fusion power, since ⟨σv⟩ for D-T rises by orders of magnitude between 5 and 20 keV.`,
  },
  ne: {
    term: "n_e — electron density",
    html: `Electrons per cubic meter. Real values (~10²⁰ m⁻³) are five to six orders of magnitude below atmospheric particle density — fusion plasmas are a near-vacuum, just extremely hot. Quasi-neutrality (n<sub>e</sub>≈n<sub>i</sub> here) is assumed throughout.`,
  },
  tauE: {
    term: "τ_E — energy confinement time",
    html: `τ<sub>E</sub> ≡ W<sub>th</sub>/P<sub>loss</sub> by definition — the e-folding time stored energy would decay on if all heating stopped. Compared against the IPB98(y,2) scaling law (0.0562·I<sub>p</sub>^0.93·B<sub>t</sub>^0.15·n̄<sub>e</sub>^0.41·P<sub>loss</sub>^-0.69·R₀^1.97·κ^0.78·ε^0.58·M^0.19) to get H<sub>98</sub>.`,
  },
  li: {
    term: "l_i — internal inductance",
    html: `l<sub>i</sub> = ⟨B<sub>θ</sub>²⟩<sub>volume</sub>/B<sub>θ</sub>²(edge), a dimensionless measure of how peaked the current-density profile is: l<sub>i</sub>=0.5 for a flat (uniform) current profile, higher for a peaked one. Affects vertical-stability margins and how much the plasma's self-inductance resists current changes.`,
  },
  POH: {
    term: "P_OH — ohmic heating",
    html: `Resistive (I²R) heating from the plasma current flowing through a finite-resistivity plasma (Spitzer resistivity, ∝T<sup>-3/2</sup>). Dominant at startup; becomes negligible once the plasma is hot enough that its resistivity drops and auxiliary heating takes over.`,
  },
  PNBI: {
    term: "P_NBI — neutral beam power",
    html: `Power from injecting high-energy (tens–hundreds of keV) neutral atoms, which ionize on entry and transfer energy to the bulk plasma via Coulomb collisions. Also a common real current-drive and momentum (rotation) source, not just heating.`,
  },
  PECHICH: {
    term: "P_ECH / P_ICH",
    html: `Electron/ion cyclotron resonance heating — microwaves at (or near a harmonic of) the local electron or ion cyclotron frequency ω<sub>c</sub>=qB/m, absorbed directly by particles gyrating in resonance. ECH is also used for precise, localized current-profile control on real devices.`,
  },
  Palpha: {
    term: "P_α — alpha heating",
    html: `Power the fusion reaction deposits back into the plasma via the charged He⁴ nucleus (the neutron escapes and carries the rest — see "Where the energy goes"). Reused directly from the burn model's already-computed charged-particle fusion power. A reactor is "ignited" when P<sub>α</sub> alone exceeds P<sub>loss</sub>, needing no external heating at all.`,
  },
  Prad: {
    term: "P_rad — radiated power",
    html: `Power lost as photons (chiefly Bremsstrahlung — free-electron deceleration in ion Coulomb fields — plus line/impurity radiation), scaling roughly as n<sub>e</sub>²√T. An unavoidable loss channel, and (deliberately) how the divertor's f<sub>det</sub> below spreads exhaust heat before it reaches any surface.`,
  },
  Ploss: {
    term: "P_loss — conducted/convected loss",
    html: `Heat and particles transported out by plasma turbulence and neoclassical (collisional) transport, rather than radiated. From the power balance dW/dt = P<sub>heat</sub>−P<sub>rad</sub>−P<sub>loss</sub>: whatever heating power isn't radiated or currently accumulating as stored energy is, by definition, P<sub>loss</sub>.`,
  },
  dWdt: {
    term: "dW/dt — stored-energy rate of change",
    html: `The transient term in the power balance above — positive while W<sub>th</sub> is ramping up (heating), ~0 once the plasma settles at a steady operating point. Computed here from the real ramp, not the burn clock, so it's ~0 at flat-top by construction.`,
  },
  PinPout: {
    term: "P_in / P_out",
    html: `P<sub>in</sub> = P<sub>OH</sub>+P<sub>NBI</sub>+P<sub>ECH</sub>+P<sub>ICH</sub>+P<sub>α</sub>; P<sub>out</sub> = P<sub>rad</sub>+P<sub>loss</sub>+dW/dt. They sum to exactly the same total by construction — a live energy-balance checksum, not two independent estimates.`,
  },
  lambdaQ: {
    term: "λ_q — SOL heat-flux width",
    html: `The radial e-folding width of the parallel heat-flux channel in the scrape-off layer at the outer midplane (Eich et al. 2013 regression: λ<sub>q</sub>[mm] = 0.63·B<sub>θ,edge</sub>[T]<sup>-1.19</sup>). Narrower at higher current/field — the central engineering tension of high-performance divertor design.`,
  },
  fdet: {
    term: "f_det — detachment fraction",
    html: `f<sub>det</sub> = P<sub>rad</sub>/(P<sub>rad</sub>+P<sub>loss</sub>), the fraction of exhaust power already radiated (typically via seeded impurities) before it would otherwise reach the target — the real technique used to protect divertor hardware from an otherwise-unmanageable heat load.`,
  },
  qi: {
    term: "q_i — peak divertor heat flux",
    html: `The perpendicular heat flux actually deposited on the target (MW/m²), after poloidal flux expansion and the shallow (~2–3°) grazing incidence angle spread the SOL's parallel heat flux over a much larger physical footprint. One of the hardest sustained thermal-engineering problems in fusion — comparable to a spacecraft heat shield, but continuous rather than a single re-entry pulse.`,
  },
  Ts: {
    term: "T_s — divertor surface temperature",
    html: `Computed via real 1D transient conduction into a semi-infinite tungsten solid under constant flux q<sub>i</sub>: ΔT = (2q<sub>i</sub>/e)√(t/π), where e=√(kρc) is tungsten's thermal effusivity. Genuinely rises with real elapsed shot time, exactly like a real target would heat up over a pulse.`,
  },
  Dalpha: {
    term: "D-α — deuterium-alpha line",
    html: `The Balmer-α (n=3→2) emission line of atomic deuterium, emitted when recycling neutrals at the plasma edge are excited and de-excite. A standard real diagnostic (a simple photodiode or camera filtered to 656 nm) and a live proxy for edge recycling/ELM activity in the shot trace.`,
  },

  // Solver-status-line terms (src/fem/equilibrium.js) -- what the "Picard: N iterations,
  // residual X, ψ_axis = Y, V = Z m³, mesh: A nodes / B tris" line under each equilibrium
  // solve actually means.
  picard: {
    term: "Picard iteration — nonlinear solve method",
    html: `The Grad–Shafranov equation is nonlinear: its source term R·p′(ψ<sub>N</sub>) + FF′(ψ<sub>N</sub>)/R depends on the normalized flux ψ<sub>N</sub> = 1−ψ/ψ<sub>axis</sub>, which isn't known until ψ itself is solved. A Picard (fixed-point) iteration handles this: solve the <em>linear</em> elliptic PDE with the source evaluated at the previous iterate's ψ, then repeat with the new ψ. The stiffness matrix depends only on mesh geometry, not ψ, so it's assembled once and reused — each iteration is a single warm-started conjugate-gradient solve, not a refactorization. The count shown is how many passes this shape/profile combination took to converge.`,
  },
  residual: {
    term: "residual — solver convergence measure",
    html: `The relative change between consecutive Picard iterates, ‖ψ<sub>new</sub>−ψ<sub>old</sub>‖₂ / ‖ψ<sub>new</sub>‖₂. The solve stops once this drops below the convergence tolerance (10⁻⁶) or a maximum iteration count is hit. A value like 4×10⁻⁷ means the last iteration changed the solution by about that fraction of its own size — well converged, not just out of iterations.`,
  },
  psiAxis: {
    term: "ψ_axis — flux at the magnetic axis",
    html: `The maximum value of the solved poloidal flux ψ over the whole mesh, at the O-point (magnetic axis) where the flux surfaces close to a single point. Every profile function — pressure, current, the fill colormap — is evaluated against the normalized flux ψ<sub>N</sub> = 1−ψ/ψ<sub>axis</sub> this defines: 0 at the axis, 1 at the boundary.`,
  },
  volumeStat: {
    term: "V — plasma volume",
    html: `Computed from the solved mesh via Pappus's theorem applied per triangle: each triangle, revolved 2π around the machine's central (vertical) axis, sweeps out a ring-shaped solid, and summing those ring volumes over the whole mesh gives the total plasma volume — using the solved (R, Z) mesh coordinates directly as meters.`,
  },
  meshStat: {
    term: "mesh — finite-element discretization",
    html: `The structured O-grid the equilibrium is solved on: rings at n<sub>ρ</sub> radial positions × n<sub>θ</sub> poloidal angles, fanned out from a single center node, with the outermost ring landing exactly on the plasma boundary (so imposing ψ=0 there is exact, not approximate). Each ring-to-ring strip splits into two triangles per quad — the node/triangle counts shown are that mesh's total size at this shape's solve resolution.`,
  },
};

// Ordered (prefix, subText) -> key patterns for the DOM-based auto-wrap pass in tooltip.js:
// a text node ending in `prefix` immediately followed by a <sub> element whose trimmed
// textContent equals `subText` gets wrapped as one glossary trigger. Order doesn't matter
// between these -- each (prefix, subText) pair is structurally distinct, so there's no
// substring-collision risk the way there would be doing this as raw string replacement.
export const SUB_PATTERNS = [
  { key: "betaN", prefix: "β", subText: "N" },
  { key: "Bt", prefix: "B", subText: "t" },
  { key: "Ip", prefix: "I", subText: "p" },
  { key: "q95", prefix: "q", subText: "95" },
  { key: "Wth", prefix: "W", subText: "th" },
  { key: "H98", prefix: "H", subText: "98" },
  { key: "Te0", prefix: "T", subText: "e0" },
  { key: "ne", prefix: "n", subText: "e" },
  { key: "tauE", prefix: "τ", subText: "E" },
  { key: "li", prefix: "l", subText: "i" },
  { key: "POH", prefix: "P", subText: "OH" },
  { key: "PNBI", prefix: "P", subText: "NBI" },
  { key: "PECHICH", prefix: "P", subText: "ECH" },
  { key: "PECHICH", prefix: "P", subText: "ICH" },
  { key: "Palpha", prefix: "P", subText: "α" },
  { key: "Prad", prefix: "P", subText: "rad" },
  { key: "Ploss", prefix: "P", subText: "loss" },
  { key: "PinPout", prefix: "P", subText: "in" },
  { key: "PinPout", prefix: "P", subText: "out" },
  { key: "lambdaQ", prefix: "λ", subText: "q" },
  { key: "fdet", prefix: "f", subText: "det" },
  { key: "qi", prefix: "q", subText: "i" },
  { key: "Ts", prefix: "T", subText: "s" },
];

// Plain literal text matches (no <sub> involved). tooltip.js runs SUB_PATTERNS before these,
// so by the time "beta" runs, every β that was immediately followed by a <sub>N</sub> has
// already been physically extracted into its own wrapped span -- what's left in any text
// node is only ever the bare symbol, no exclusion logic needed here.
export const TEXT_PATTERNS = [
  { key: "Hmode", text: "H-mode" },
  { key: "Hmode", text: "L-mode" },
  { key: "dWdt", text: "dW/dt" },
  { key: "Dalpha", text: "D-α" },
  { key: "beta", text: "β" },
];
